### Get greeting
GET {{host}}/greeting
Authorization: Basic user password

### Update greeting
PUT {{host}}/greeting
Authorization: Basic user password
Content-Type: application/json

{
  "message": "new greeting",
  "lastVersion": 0
}
